apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibloginspa
  labels:
    app: ibloginspa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibloginspa
  template:
    metadata:
      labels:
        app: ibloginspa
    spec:
      containers:
      - name: ibloginspa
        image: longquang/webserver
        ports:
        - containerPort: 30344
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ibloginspa-service"
  namespace: "mywebserver"
  labels:
    app: "ibloginspa"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "ibloginspa"
  type: "LoadBalancer"
  loadBalancerIP: ""

        
        


